/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as LacesRouteImport } from './routes/laces'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SizeChartRouteImport } from './routes/size-chart'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthVerifyRouteImport } from './routes/_auth.verify'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin/admin.categories'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin/admin.coupons'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin/admin.products'
import { Route as AdminAdminOrdersOrderIdRouteImport } from './routes/_admin/admin.orders.$orderId'
import { Route as AdminAdminProductsProductIdRouteImport } from './routes/_admin/admin.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const LacesRoute = LacesRouteImport.update({
  id: '/laces',
  path: '/laces',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeChartRoute = SizeChartRouteImport.update({
  id: '/size-chart',
  path: '/size-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOrdersOrderIdRoute = AdminAdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminAdminOrdersRoute,
} as any)
const AdminAdminProductsProductIdRoute =
  AdminAdminProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AdminAdminProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/addresses': typeof AddressesRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/custom': typeof CustomRoute
  '/laces': typeof LacesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/size-chart': typeof SizeChartRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminAdminProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/addresses': typeof AddressesRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/custom': typeof CustomRoute
  '/laces': typeof LacesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/size-chart': typeof SizeChartRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
  '/admin/products/$productId': typeof AdminAdminProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/accessories': typeof AccessoriesRoute
  '/addresses': typeof AddressesRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRoute
  '/custom': typeof CustomRoute
  '/laces': typeof LacesRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/size-chart': typeof SizeChartRoute
  '/wishlist': typeof WishlistRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/_admin/admin/products': typeof AdminAdminProductsRouteWithChildren
  '/_admin/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
  '/_admin/admin/products/$productId': typeof AdminAdminProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/addresses'
    | '/brands'
    | '/checkout'
    | '/custom'
    | '/laces'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reviews'
    | '/size-chart'
    | '/wishlist'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/addresses'
    | '/brands'
    | '/checkout'
    | '/custom'
    | '/laces'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reviews'
    | '/size-chart'
    | '/wishlist'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/orders/$orderId'
    | '/admin/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/accessories'
    | '/addresses'
    | '/brands'
    | '/checkout'
    | '/custom'
    | '/laces'
    | '/orders'
    | '/products'
    | '/profile'
    | '/reviews'
    | '/size-chart'
    | '/wishlist'
    | '/_admin/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/_admin/admin/categories'
    | '/_admin/admin/coupons'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/orders/$orderId'
    | '/_admin/admin/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AccessoriesRoute: typeof AccessoriesRoute
  AddressesRoute: typeof AddressesRoute
  BrandsRoute: typeof BrandsRoute
  CheckoutRoute: typeof CheckoutRoute
  CustomRoute: typeof CustomRoute
  LacesRoute: typeof LacesRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  SizeChartRoute: typeof SizeChartRoute
  WishlistRoute: typeof WishlistRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laces': {
      id: '/laces'
      path: '/laces'
      fullPath: '/laces'
      preLoaderRoute: typeof LacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-chart': {
      id: '/size-chart'
      path: '/size-chart'
      fullPath: '/size-chart'
      preLoaderRoute: typeof SizeChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/coupons': {
      id: '/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/orders/$orderId': {
      id: '/_admin/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminAdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminAdminOrdersRoute
    }
    '/_admin/admin/products/$productId': {
      id: '/_admin/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminAdminProductsProductIdRouteImport
      parentRoute: typeof AdminAdminProductsRoute
    }
  }
}

interface AdminAdminOrdersRouteChildren {
  AdminAdminOrdersOrderIdRoute: typeof AdminAdminOrdersOrderIdRoute
}

const AdminAdminOrdersRouteChildren: AdminAdminOrdersRouteChildren = {
  AdminAdminOrdersOrderIdRoute: AdminAdminOrdersOrderIdRoute,
}

const AdminAdminOrdersRouteWithChildren =
  AdminAdminOrdersRoute._addFileChildren(AdminAdminOrdersRouteChildren)

interface AdminAdminProductsRouteChildren {
  AdminAdminProductsProductIdRoute: typeof AdminAdminProductsProductIdRoute
}

const AdminAdminProductsRouteChildren: AdminAdminProductsRouteChildren = {
  AdminAdminProductsProductIdRoute: AdminAdminProductsProductIdRoute,
}

const AdminAdminProductsRouteWithChildren =
  AdminAdminProductsRoute._addFileChildren(AdminAdminProductsRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRouteWithChildren
  AdminAdminProductsRoute: typeof AdminAdminProductsRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRouteWithChildren,
  AdminAdminProductsRoute: AdminAdminProductsRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AccessoriesRoute: AccessoriesRoute,
  AddressesRoute: AddressesRoute,
  BrandsRoute: BrandsRoute,
  CheckoutRoute: CheckoutRoute,
  CustomRoute: CustomRoute,
  LacesRoute: LacesRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  SizeChartRoute: SizeChartRoute,
  WishlistRoute: WishlistRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
