/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthSignInRouteImport } from './routes/_auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth.sign-up'
import { Route as AuthVerifyRouteImport } from './routes/_auth.verify'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminOrdersOrderIdRouteImport } from './routes/_admin/admin.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminOrdersOrderIdRoute = AdminAdminOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AdminAdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/dashboard': typeof AdminDashboardRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/addresses': typeof AddressesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify': typeof AuthVerifyRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRouteWithChildren
  '/_admin/admin/orders/$orderId': typeof AdminAdminOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/checkout'
    | '/orders'
    | '/products'
    | '/profile'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/admin/orders'
    | '/admin/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/checkout'
    | '/orders'
    | '/products'
    | '/profile'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/admin/orders'
    | '/admin/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/addresses'
    | '/checkout'
    | '/orders'
    | '/products'
    | '/profile'
    | '/_admin/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify'
    | '/order-confirmation/$orderId'
    | '/orders/$orderId'
    | '/products/$slug'
    | '/_admin/admin/orders'
    | '/_admin/admin/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AddressesRoute: typeof AddressesRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify': {
      id: '/_auth/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/orders/$orderId': {
      id: '/_admin/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminAdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminAdminOrdersRoute
    }
  }
}

interface AdminAdminOrdersRouteChildren {
  AdminAdminOrdersOrderIdRoute: typeof AdminAdminOrdersOrderIdRoute
}

const AdminAdminOrdersRouteChildren: AdminAdminOrdersRouteChildren = {
  AdminAdminOrdersOrderIdRoute: AdminAdminOrdersOrderIdRoute,
}

const AdminAdminOrdersRouteWithChildren =
  AdminAdminOrdersRoute._addFileChildren(AdminAdminOrdersRouteChildren)

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AddressesRoute: AddressesRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
